name: 'Terraform PR'
description: 'GitHub Action for adding `terraform plan` output as a PR comment'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        terraform plan -no-color 2>&1 | tee ${GITHUB_WORKSPACE}/plan.out

    - name: Create/Update Comment
      uses: actions/github-script@v6
      env:
        TF_WORKSPACE: "${{ steps.workspace.outputs.stdout }}"
        CUSTOM_TITLE: "${{ inputs.pr-comment-title }}"
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          if (!context || !context.issue || !context.issue.number) {
            return;
          }

          const tag = [
            process.env.CUSTOM_TITLE,
            process.env.TF_WORKSPACE,
          ]
            .filter(s => !!s)
            .join(" ");

          const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
          const run_link = '<a href="' + run_url + '">Actions</a>.'
          const fs = require('fs')
          const raw_plan = fs.readFileSync('plan.out', 'utf8')
          const plan = raw_plan.length > 65000 ? " ..." + raw_plan.toString().substring(raw_plan.length - 65000, raw_plan.length) : raw_plan
          const truncated_message = raw_plan.length > 65000 ? "Output is too long and was truncated. You can read full Plan in " + run_link + "<br /><br />" : ""

          const commentTitle = `### Terraform Status ${tag}`;
          const commentContent = `
          ${commentTitle}
          #### Terraform Format and Style 🖌 \`${{ steps.fmt.outputs.fmt-outcome }}\`
          #### Terraform Validate 📖 \`${{ steps.validate.outputs.validate-outcome }}\`
          #### Terraform Plan 📖 \`${{ steps.plan.outputs.plan-outcome }}\`
          <details>
          <summary>Show Plan</summary>

          \`\`\`
          ${plan}
          \`\`\`

          </details>
          ${truncated_message}

          Pusher: @${{ github.actor }}
          Action: \`${{ github.event_name }}\`
          `;

          const comments = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const githubActionsBotComment = comments.data.find(comment =>
            comment.user.login === 'github-actions[bot]' &&
             comment.body.includes(commentTitle)
          );

          if (raw_plan.includes("No changes.")) {
            if (githubActionsBotComment) {
              await github.rest.issues.deleteComment({
                comment_id: githubActionsBotComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            }
          } else {
            if (githubActionsBotComment) {
              await github.rest.issues.updateComment({
                comment_id: githubActionsBotComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentContent,
              })
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentContent,
              })
            }
          }

    - name: Terraform Validate Status
      shell: bash
      run: |
        if [[ '${{ inputs.require-validate }}' == 'true' ]] && [[ '${{ steps.validate.outputs.validate-outcome }}' == 'failure' ]]; then
          cat <<"EOFFFF"
          ${{ steps.validate.outputs.stdout }}
          ${{ steps.validate.outputs.stderr }}
        EOFFFF
          exit 1
        fi

    - name: Terraform Plan Status
      shell: bash
      run: |
        if [[ '${{ steps.plan.outputs.plan-outcome }}' == 'failure' ]]; then
          cat <<"EOFFFF"
          ${{ steps.plan.outputs.stdout }}
          ${{ steps.plan.outputs.stderr }}
        EOFFFF
          exit 1
        fi

    - name: Terraform Format Status
      shell: bash
      run: |
        if [[ '${{ inputs.require-formatting }}' == 'true' ]] && [[ '${{ steps.fmt.outputs.fmt-outcome }}' == 'failure' ]]; then
          cat <<"EOFFFF"
          ${{ steps.fmt.outputs.stdout }}
          ${{ steps.fmt.outputs.stderr }}
        EOFFFF
          exit 1
        fi

    - name: Terraform Apply
      shell: bash
      run: |
        if [[ '${{ github.ref }}' != 'refs/heads/${{ inputs.apply-branch }}' ]]
        then
          echo
          echo
          echo "********"
          echo "Branch is not '${{ inputs.apply-branch }}', 'terraform apply' will not be executed."
          echo "********"
          echo
          exit 0
        fi

        # Update remote references
        git fetch --quiet

        if [[ "$(git rev-parse origin/${{ github.ref_name }})" != "$(git rev-parse HEAD)" ]]
        then
          echo
          echo
          echo "********"
          echo "Branch '${{ inputs.apply-branch }}' is not up to date, 'terraform apply' will not be executed."
          echo "Please run only run this action on the latest commit on the '${{ inputs.apply-branch }}' branch."
          echo "********"
          echo
          exit 1
        fi

        cd ${{ inputs.path }}
        terraform apply -lock-timeout=60s -auto-approve
