name: 'Terraform PR'
description: 'GitHub Action for adding `terraform plan` output as a PR comment'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  working-directory:
    description: 'Directory to run terraform plan in'
    required: false
    default: '.'
  pr-comment-title:
    description: 'Custom title for the PR comment (useful for monorepos)'
    required: false
    default: 'Terraform Plan'
runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -o pipefail
        terraform plan -no-color 2>&1 | tee ${GITHUB_WORKSPACE}/plan.out

    - name: Create/Update Comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const raw_plan = fs.readFileSync('plan.out', 'utf8');
          const commentTitle = `${{ inputs.pr-comment-title }}`;
          
          // GitHub comment limit is 65535 characters
          const maxLength = 60000;
          let planOutput = raw_plan;
          let truncated = false;
          
          if (planOutput.length > maxLength) {
            planOutput = planOutput.substring(0, maxLength);
            truncated = true;
          }
          
          let commentContent = `${commentTitle}\n\`\`\`\n${planOutput}\n\`\`\``;
          
          if (truncated) {
            commentContent += `\n\n⚠️ **Output truncated** - plan output exceeded ${maxLength} characters. See workflow logs for full output.`;
          }
          
          const comments = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          const githubActionsBotComment = comments.data.find(comment =>
            comment.user.login === 'github-actions[bot]' &&
             comment.body.includes(commentTitle)
          );
          
          if (githubActionsBotComment) {
            await github.rest.issues.updateComment({
              comment_id: githubActionsBotComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentContent,
            })
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentContent,
            })
          }
